#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsmbios
Version  : 2.4.1
Release  : 1
URL      : https://github.com/dell/libsmbios/archive/v2.4.1.tar.gz
Source0  : https://github.com/dell/libsmbios/archive/v2.4.1.tar.gz
Summary  : C libraries for accessing dmi data
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 OSL-2.0
Requires: libsmbios-bin
Requires: libsmbios-python3
Requires: libsmbios-lib
Requires: libsmbios-locales
Requires: libsmbios-doc
Requires: libsmbios-data
Requires: libsmbios-python
BuildRequires : doxygen
BuildRequires : gettext
BuildRequires : graphviz
BuildRequires : help2man
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(libxml-2.0)

%description
We have decided to use a boost-style configuration system for libsmbios. The
headers in and below this directory are mostly imported from boost with all
"BOOST" prefixes changed to LIBSMBIOS.

%package bin
Summary: bin components for the libsmbios package.
Group: Binaries
Requires: libsmbios-data

%description bin
bin components for the libsmbios package.


%package data
Summary: data components for the libsmbios package.
Group: Data

%description data
data components for the libsmbios package.


%package dev
Summary: dev components for the libsmbios package.
Group: Development
Requires: libsmbios-lib
Requires: libsmbios-bin
Requires: libsmbios-data
Provides: libsmbios-devel

%description dev
dev components for the libsmbios package.


%package doc
Summary: doc components for the libsmbios package.
Group: Documentation

%description doc
doc components for the libsmbios package.


%package lib
Summary: lib components for the libsmbios package.
Group: Libraries
Requires: libsmbios-data

%description lib
lib components for the libsmbios package.


%package locales
Summary: locales components for the libsmbios package.
Group: Default

%description locales
locales components for the libsmbios package.


%package python
Summary: python components for the libsmbios package.
Group: Default
Requires: libsmbios-python3

%description python
python components for the libsmbios package.


%package python3
Summary: python3 components for the libsmbios package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libsmbios package.


%prep
%setup -q -n libsmbios-2.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525543191
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1525543191
rm -rf %{buildroot}
%make_install
%find_lang libsmbios

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/smbios-battery-ctl
/usr/bin/smbios-get-ut-data
/usr/bin/smbios-keyboard-ctl
/usr/bin/smbios-lcd-brightness
/usr/bin/smbios-passwd
/usr/bin/smbios-state-byte-ctl
/usr/bin/smbios-sys-info
/usr/bin/smbios-sys-info-lite
/usr/bin/smbios-thermal-ctl
/usr/bin/smbios-token-ctl
/usr/bin/smbios-upflag-ctl
/usr/bin/smbios-wakeup-ctl
/usr/bin/smbios-wireless-ctl

%files data
%defattr(-,root,root,-)
/usr/share/smbios-utils/__pycache__/cli.cpython-36.pyc
/usr/share/smbios-utils/cli.py
/usr/share/smbios-utils/token_blacklist.csv
/usr/share/smbios-utils/token_list.csv

%files dev
%defattr(-,root,root,-)
/usr/lib64/libsmbios_c.so
/usr/lib64/pkgconfig/libsmbios_c.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsmbios_c.so.2
/usr/lib64/libsmbios_c.so.2.2.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f libsmbios.lang
%defattr(-,root,root,-)

